-- ============================================================
-- Smart Office Seat Occupancy — Supabase Schema + Seed Data
-- Run this entire file in: Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. Tables
create table if not exists seats (
  id          text primary key,
  label       text not null,
  floor       text not null default 'main-floor',
  status      text not null default 'free' check (status in ('free', 'occupied', 'reserved')),
  occupant    jsonb,
  department  text,
  "table"     text,
  color       text
);

create table if not exists employees (
  id          bigint generated by default as identity primary key,
  name        text not null,
  department  text not null,
  seat        text references seats(id),
  "table"     text,
  "checkIn"   text,
  wfh         boolean not null default false
);

create table if not exists settings (
  key   text primary key,
  value jsonb not null
);

-- 2. Row Level Security (anon key can read and write — admin auth is in the UI)
alter table seats     enable row level security;
alter table employees enable row level security;
alter table settings  enable row level security;

drop policy if exists "seats_all"     on seats;
drop policy if exists "employees_all" on employees;
drop policy if exists "settings_all"  on settings;

create policy "seats_all"     on seats     for all to anon using (true) with check (true);
create policy "employees_all" on employees for all to anon using (true) with check (true);
create policy "settings_all"  on settings  for all to anon using (true) with check (true);

-- 3. Seed — Seats (56 desks)
insert into seats (id, label, floor, status, occupant, department, "table", color) values
  ('Desk 1',  'Desk 1',  'main-floor', 'occupied', '{"name":"Sujay Bhonsle","department":"CS"}',           'CS',     'Table 1', null),
  ('Desk 2',  'Desk 2',  'main-floor', 'occupied', '{"name":"Smriti Tewari","department":"CS"}',           'CS',     'Table 1', null),
  ('Desk 3',  'Desk 3',  'main-floor', 'occupied', '{"name":"Blaise Vaz","department":"CS"}',              'CS',     'Table 1', null),
  ('Desk 4',  'Desk 4',  'main-floor', 'occupied', '{"name":"Jyoti Nair","department":"CS"}',              'CS',     'Table 1', null),
  ('Desk 5',  'Desk 5',  'main-floor', 'occupied', '{"name":"Bhagyashree Shah","department":"CS"}',        'CS',     'Table 1', null),
  ('Desk 6',  'Desk 6',  'main-floor', 'occupied', '{"name":"Nilesh Singh Bashera","department":"CS"}',    'CS',     'Table 1', null),
  ('Desk 7',  'Desk 7',  'main-floor', 'occupied', '{"name":"Chandni Upadhyay","department":"CS"}',        'CS',     'Table 1', null),
  ('Desk 8',  'Desk 8',  'main-floor', 'occupied', '{"name":"Pranjal Agarwal","department":"CS"}',         'CS',     'Table 1', null),
  ('Desk 9',  'Desk 9',  'main-floor', 'occupied', '{"name":"Srushti Chawhan","department":"CS"}',         'CS',     'Table 1', null),
  ('Desk 10', 'Desk 10', 'main-floor', 'occupied', '{"name":"Nathanial Siqueira Vaz","department":"CS"}',  'CS',     'Table 1', null),
  ('Desk 11', 'Desk 11', 'main-floor', 'occupied', '{"name":"Dhruti Maru","department":"CS"}',             'CS',     'Table 1', null),
  ('Desk 12', 'Desk 12', 'main-floor', 'occupied', '{"name":"Dhyan Ramnani","department":"CS"}',           'CS',     'Table 1', null),
  ('Desk 13', 'Desk 13', 'main-floor', 'occupied', '{"name":"Rupesh Doiphode","department":"Art"}',        'Art',    'Table 2', null),
  ('Desk 14', 'Desk 14', 'main-floor', 'occupied', '{"name":"Yogesh More","department":"Art"}',            'Art',    'Table 2', null),
  ('Desk 15', 'Desk 15', 'main-floor', 'occupied', '{"name":"Rahul Kumawat","department":"Art"}',          'Art',    'Table 2', null),
  ('Desk 16', 'Desk 16', 'main-floor', 'occupied', '{"name":"Masumi Shrimankar","department":"Art"}',      'Art',    'Table 2', null),
  ('Desk 17', 'Desk 17', 'main-floor', 'occupied', '{"name":"Dhruvi Shah","department":"Art"}',            'Art',    'Table 2', null),
  ('Desk 18', 'Desk 18', 'main-floor', 'occupied', '{"name":"Sonali Sawant","department":"Art"}',          'Art',    'Table 2', null),
  ('Desk 19', 'Desk 19', 'main-floor', 'occupied', '{"name":"Sushant Agare","department":"Art"}',          'Art',    'Table 2', null),
  ('Desk 20', 'Desk 20', 'main-floor', 'occupied', '{"name":"Amey Lad","department":"Art"}',               'Art',    'Table 2', null),
  ('Desk 21', 'Desk 21', 'main-floor', 'occupied', '{"name":"Kiran Salkar","department":"Art"}',           'Art',    'Table 2', null),
  ('Desk 22', 'Desk 22', 'main-floor', 'occupied', '{"name":"Atharva Salvi","department":"Art"}',          'Art',    'Table 2', null),
  ('Desk 23', 'Desk 23', 'main-floor', 'occupied', '{"name":"Subodh Chaubey","department":"Copy"}',        'Copy',   'Table 3', null),
  ('Desk 24', 'Desk 24', 'main-floor', 'occupied', '{"name":"Ryan Parkar","department":"Copy"}',           'Copy',   'Table 3', null),
  ('Desk 25', 'Desk 25', 'main-floor', 'occupied', '{"name":"Ritwik Mishra","department":"Copy"}',         'Copy',   'Table 3', null),
  ('Desk 26', 'Desk 26', 'main-floor', 'occupied', '{"name":"Sanjit Samant","department":"Copy"}',         'Copy',   'Table 3', null),
  ('Desk 27', 'Desk 27', 'main-floor', 'occupied', '{"name":"Anarghya Poojary","department":"Copy"}',      'Copy',   'Table 3', null),
  ('Desk 28', 'Desk 28', 'main-floor', 'occupied', '{"name":"Juhi Pravin Shah","department":"Copy"}',      'Copy',   'Table 3', null),
  ('Desk 29', 'Desk 29', 'main-floor', 'occupied', '{"name":"Gaurav Pant","department":"Copy"}',           'Copy',   'Table 3', null),
  ('Desk 30', 'Desk 30', 'main-floor', 'occupied', '{"name":"Aditya Salve","department":"Copy"}',          'Copy',   'Table 3', null),
  ('Desk 31', 'Desk 31', 'main-floor', 'occupied', '{"name":"Viraj Chorghe","department":"Flims"}',        'Films',  'Table 4', null),
  ('Desk 32', 'Desk 32', 'main-floor', 'occupied', '{"name":"Varun Lalka","department":"Flims"}',          'Films',  'Table 4', null),
  ('Desk 33', 'Desk 33', 'main-floor', 'occupied', '{"name":"Darryl Gomes","department":"Flims"}',         'Films',  'Table 4', null),
  ('Desk 34', 'Desk 34', 'main-floor', 'occupied', '{"name":"Ashok Chatla","department":"Flims"}',         'Films',  'Table 4', null),
  ('Desk 35', 'Desk 35', 'main-floor', 'occupied', '{"name":"Raj Kolambkar","department":"Flims"}',        'Films',  'Table 4', null),
  ('Desk 36', 'Desk 36', 'main-floor', 'occupied', '{"name":"Avishkar Mandavkar","department":"Flims"}',   'Films',  'Table 4', null),
  ('Desk 37', 'Desk 37', 'main-floor', 'occupied', '{"name":"Bhaskar Wooragonda","department":"Flims"}',   'Films',  'Table 4', null),
  ('Desk 38', 'Desk 38', 'main-floor', 'occupied', '{"name":"Dattaram Kambli","department":"Studio"}',     'Studio', 'Table 5', null),
  ('Desk 39', 'Desk 39', 'main-floor', 'occupied', '{"name":"Biju Dasan","department":"Studio"}',          'Studio', 'Table 5', null),
  ('Desk 40', 'Desk 40', 'main-floor', 'occupied', '{"name":"Uday Panchal","department":"Studio"}',        'Studio', 'Table 5', null),
  ('Desk 41', 'Desk 41', 'main-floor', 'occupied', '{"name":"Ashish Kumbhar","department":"Studio"}',      'Studio', 'Table 5', null),
  ('Desk 42', 'Desk 42', 'main-floor', 'occupied', '{"name":"Navnath Bhere","department":"Studio"}',       'Studio', 'Table 5', null),
  ('Desk 43', 'Desk 43', 'main-floor', 'occupied', '{"name":"Rajesh K Bhardwaj","department":"Studio"}',   'Studio', 'Table 5', null),
  ('Desk 44', 'Desk 44', 'main-floor', 'occupied', '{"name":"Abhishek Shelar","department":"Studio"}',     'Studio', 'Table 5', null),
  ('Desk 45', 'Desk 45', 'main-floor', 'occupied', '{"name":"Meghna Gambhir","department":"Digital"}',     'Digital','Table 6', null),
  ('Desk 46', 'Desk 46', 'main-floor', 'occupied', '{"name":"Amaan Khan","department":"Digital"}',         'Digital','Table 6', null),
  ('Desk 47', 'Desk 47', 'main-floor', 'occupied', '{"name":"Mohit Devganiya","department":"Digital"}',    'Digital','Table 6', null),
  ('Desk 48', 'Desk 48', 'main-floor', 'occupied', '{"name":"Prem Gohil","department":"Digital"}',         'Digital','Table 6', null),
  ('Desk 49', 'Desk 49', 'main-floor', 'occupied', '{"name":"Gaurav Gohil","department":"Digital"}',       'Digital','Table 6', null),
  ('Desk 50', 'Desk 50', 'main-floor', 'occupied', '{"name":"Nitesh Kumar","department":"Digital"}',       'Digital','Table 6', null),
  ('Desk 51', 'Desk 51', 'main-floor', 'occupied', '{"name":"Aanchal Choudhary","department":"Digital"}',  'Digital','Table 6', null),
  ('Desk 52', 'Desk 52', 'main-floor', 'occupied', '{"name":"Jennifer Sequeira","department":"Digital"}',  'Digital','Table 6', null),
  ('Desk 53', 'Desk 53', 'main-floor', 'occupied', '{"name":"Vidya Sridhar","department":"Digital"}',      'Digital','Table 6', null),
  ('Desk 54', 'Desk 54', 'main-floor', 'occupied', '{"name":"Mahesh Tanawde","department":"Digital"}',     'Digital','Table 6', null),
  ('Desk 55', 'Desk 55', 'main-floor', 'occupied', '{"name":"Yatin Ashok Mhatre","department":"Digital"}', 'Digital','Table 6', null),
  ('Desk 56', 'Desk 56', 'main-floor', 'occupied', '{"name":"Akshita Datir","department":"Digital"}',      'Digital','Table 6', null)
on conflict (id) do nothing;

-- 4. Seed — Employees (68 people)
insert into employees (id, name, department, seat, "table", "checkIn", wfh) values
  (1,  'Sujay Bhonsle',        'CS',      'Desk 1',  'Table 1', '09:11 AM', false),
  (2,  'Smriti Tewari',        'CS',      'Desk 2',  'Table 1', '09:12 AM', false),
  (3,  'Blaise Vaz',           'CS',      'Desk 3',  'Table 1', '09:13 AM', false),
  (4,  'Viraj Chorghe',        'Flims',   'Desk 31', 'Table 4', '09:14 AM', false),
  (5,  'Varun Lalka',          'Flims',   'Desk 32', 'Table 4', '09:15 AM', false),
  (6,  'Darryl Gomes',         'Flims',   'Desk 33', 'Table 4', '09:16 AM', false),
  (7,  'Ashok Chatla',         'Flims',   'Desk 34', 'Table 4', '09:17 AM', false),
  (8,  'Raj Kolambkar',        'Flims',   'Desk 35', 'Table 4', '09:18 AM', false),
  (9,  'Avishkar Mandavkar',   'Flims',   'Desk 36', 'Table 4', '09:19 AM', false),
  (10, 'Bhaskar Wooragonda',   'Flims',   'Desk 37', 'Table 4', '09:20 AM', false),
  (11, 'Rupesh Doiphode',      'Art',     'Desk 13', 'Table 2', '09:21 AM', false),
  (12, 'Yogesh More',          'Art',     'Desk 14', 'Table 2', '09:22 AM', false),
  (13, 'Rahul Kumawat',        'Art',     'Desk 15', 'Table 2', '09:23 AM', false),
  (14, 'Masumi Shrimankar',    'Art',     'Desk 16', 'Table 2', '09:24 AM', false),
  (15, 'Dhruvi Shah',          'Art',     'Desk 17', 'Table 2', '09:25 AM', false),
  (16, 'Sonali Sawant',        'Art',     'Desk 18', 'Table 2', '09:26 AM', false),
  (17, 'Sushant Agare',        'Art',     'Desk 19', 'Table 2', '09:27 AM', false),
  (18, 'Amey Lad',             'Art',     'Desk 20', 'Table 2', '09:28 AM', false),
  (19, 'Kiran Salkar',         'Art',     'Desk 21', 'Table 2', '09:29 AM', false),
  (20, 'Atharva Salvi',        'Art',     'Desk 22', 'Table 2', '09:30 AM', false),
  (21, 'Siya Pandit',          'Art',     null,      'No desk', '09:31 AM', true),
  (22, 'Sumedh Sawant',        'Art',     null,      'No desk', '09:32 AM', true),
  (23, 'Subodh Chaubey',       'Copy',    'Desk 23', 'Table 3', '09:33 AM', false),
  (24, 'Ryan Parkar',          'Copy',    'Desk 24', 'Table 3', '09:34 AM', false),
  (25, 'Ritwik Mishra',        'Copy',    'Desk 25', 'Table 3', '09:35 AM', false),
  (26, 'Sanjit Samant',        'Copy',    'Desk 26', 'Table 3', '09:36 AM', false),
  (27, 'Anarghya Poojary',     'Copy',    'Desk 27', 'Table 3', '09:37 AM', false),
  (28, 'Juhi Pravin Shah',     'Copy',    'Desk 28', 'Table 3', '09:38 AM', false),
  (29, 'Gaurav Pant',          'Copy',    'Desk 29', 'Table 3', '09:39 AM', false),
  (30, 'Aditya Salve',         'Copy',    'Desk 30', 'Table 3', '09:40 AM', false),
  (31, 'Jyoti Nair',           'CS',      'Desk 4',  'Table 1', '09:41 AM', false),
  (32, 'Bhagyashree Shah',     'CS',      'Desk 5',  'Table 1', '09:42 AM', false),
  (33, 'Nilesh Singh Bashera', 'CS',      'Desk 6',  'Table 1', '09:43 AM', false),
  (34, 'Chandni Upadhyay',     'CS',      'Desk 7',  'Table 1', '09:44 AM', false),
  (35, 'Pranjal Agarwal',      'CS',      'Desk 8',  'Table 1', '09:45 AM', false),
  (36, 'Srushti Chawhan',      'CS',      'Desk 9',  'Table 1', '09:46 AM', false),
  (37, 'Nathanial Siqueira Vaz','CS',     'Desk 10', 'Table 1', '09:47 AM', false),
  (38, 'Dhruti Maru',          'CS',      'Desk 11', 'Table 1', '09:48 AM', false),
  (39, 'Dhyan Ramnani',        'CS',      'Desk 12', 'Table 1', '09:49 AM', false),
  (40, 'Jayalaxmi Ravi',       'CS',      null,      'No desk', '09:10 AM', true),
  (41, 'Abhay Khabale',        'CS',      null,      'No desk', '09:11 AM', true),
  (42, 'Steffi Barboza',       'CS',      null,      'No desk', '09:12 AM', true),
  (43, 'Tarun Kamath',         'CS',      null,      'No desk', '09:13 AM', true),
  (44, 'Kshitij Bidvai',       'CS',      null,      'No desk', '09:14 AM', true),
  (45, 'Anoushka Kabre',       'CS',      null,      'No desk', '09:15 AM', true),
  (46, 'Dattaram Kambli',      'Studio',  'Desk 38', 'Table 5', '09:16 AM', false),
  (47, 'Biju Dasan',           'Studio',  'Desk 39', 'Table 5', '09:17 AM', false),
  (48, 'Uday Panchal',         'Studio',  'Desk 40', 'Table 5', '09:18 AM', false),
  (49, 'Ashish Kumbhar',       'Studio',  'Desk 41', 'Table 5', '09:19 AM', false),
  (50, 'Navnath Bhere',        'Studio',  'Desk 42', 'Table 5', '09:20 AM', false),
  (51, 'Rajesh K Bhardwaj',    'Studio',  'Desk 43', 'Table 5', '09:21 AM', false),
  (52, 'Abhishek Shelar',      'Studio',  'Desk 44', 'Table 5', '09:22 AM', false),
  (53, 'Sunil Saundalkar',     'Studio',  null,      'No desk', '09:23 AM', true),
  (54, 'Meghna Gambhir',       'Digital', 'Desk 45', 'Table 6', '09:24 AM', false),
  (55, 'Amaan Khan',           'Digital', 'Desk 46', 'Table 6', '09:25 AM', false),
  (56, 'Mohit Devganiya',      'Digital', 'Desk 47', 'Table 6', '09:26 AM', false),
  (57, 'Prem Gohil',           'Digital', 'Desk 48', 'Table 6', '09:27 AM', false),
  (58, 'Gaurav Gohil',         'Digital', 'Desk 49', 'Table 6', '09:28 AM', false),
  (59, 'Nitesh Kumar',         'Digital', 'Desk 50', 'Table 6', '09:29 AM', false),
  (60, 'Aanchal Choudhary',    'Digital', 'Desk 51', 'Table 6', '09:30 AM', false),
  (61, 'Jennifer Sequeira',    'Digital', 'Desk 52', 'Table 6', '09:31 AM', false),
  (62, 'Vidya Sridhar',        'Digital', 'Desk 53', 'Table 6', '09:32 AM', false),
  (63, 'Mahesh Tanawde',       'Digital', 'Desk 54', 'Table 6', '09:33 AM', false),
  (64, 'Yatin Ashok Mhatre',   'Digital', 'Desk 55', 'Table 6', '09:34 AM', false),
  (65, 'Akshita Datir',        'Digital', 'Desk 56', 'Table 6', '09:35 AM', false),
  (66, 'Intern 1',             'Digital', null,      'No desk', '09:36 AM', true),
  (67, 'Intern 2',             'Digital', null,      'No desk', '09:36 AM', true),
  (68, 'Intern 3',             'Digital', null,      'No desk', '09:36 AM', true)
on conflict (id) do nothing;

-- 5. Reset sequence so new employees get IDs starting from 69
select setval(pg_get_serial_sequence('employees', 'id'), max(id)) from employees;
