-- ============================================================
-- Meeting Rooms — run in Supabase Dashboard → SQL Editor
-- Run this AFTER the main supabase-schema.sql
-- ============================================================

create table if not exists meeting_rooms (
  id           bigint generated by default as identity primary key,
  name         text not null,
  capacity     int not null,
  status       text not null default 'available' check (status in ('available', 'booked')),
  booked_by    text,
  booked_until timestamptz
);

alter table meeting_rooms enable row level security;
drop policy if exists "rooms_all" on meeting_rooms;
create policy "rooms_all" on meeting_rooms for all to anon using (true) with check (true);

insert into meeting_rooms (name, capacity) values
  ('Board Room',        12),
  ('Conference Room A',  8),
  ('Conference Room B',  6),
  ('Huddle Room 1',      4),
  ('Huddle Room 2',      4)
on conflict do nothing;
